background                = "#0B0812"
background-alpha          = 0.93
text                      = "#F0ECE4"
border                    = "rgba(8F4BC8ee) rgba(9CF23Aee) 45deg"
border-alpha              = 1.0
scrim                     = "#06040A"
scrim-alpha               = 0.62
selected-background       = "#3B2470"
selected-background-alpha = 0.48
selected-text             = "#5CFFAE"
selected-border           = "#00FF88"
selected-border-alpha     = 0.9
